import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Docusaurus-recommended approach: one autogenerated sidebar.
 * Directory labels and ordering are controlled by _category_.json
 * files in each directory. Page ordering uses sidebar_position
 * frontmatter. Zero maintenance — new pages and directories are
 * picked up automatically.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
