import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'charlie-kirk',
    {
      type: 'category',
      label: 'Timeline',
      collapsed: false,
      items: [
        'Timeline/overview',
        'Timeline/Charlie_Kirk',
        'Timeline/Sept_8_to_13',
        'Timeline/Tyler_Robinson/2025_Sept',
        'Timeline/Tyler_Robinson/Mirandizing',
        'Timeline/Tyler_Robinson/Affidavit_Probable_Cause',
      ],
    },
    'Topics',
    'Topic-Analyses',
    'Topics3/overview',

    // Investigation Sections (flattened to top level)
    'analysis_documentation/overview',
    'timeline_events/overview',
    'key_individuals/overview',
    'aircraft_flight_analysis/overview',
    'technology_surveillance/overview',
    'social_media_analysis/overview',
    'government_organizations/overview',
    'legal_investigation/overview',
    'security_law_enforcement/overview',
    'political_context/overview',
    'media_response/overview',
    'campus_university/overview',
    'conspiracy_theories/overview',
    'organizations_groups/overview',
    'property_locations/overview',
    'other_topics/overview',

    // Home page three-column bullet list items
    'Charlie/overview',
    'Charlie/Autopsy',
    'Killer/overview',
    'Motive/overview',
    'Israel/overview',
    'Tyler_Robinson/overview',
    'Tyler_Robinson/Trial/overview',
    'Tyler/shooting/overview',
    'Tyler/Before',
    'Vote/overview',
    'Fix/overview',
    'Fix/Politicans',
    'FBI/overview',
    'CIA/overview',
    'CoverUp/overview',
    'Censorship/overview',
    'Theories/overview',
    'Planes/overview',
    'Drones/overview',
    'Shooting_Locations/overview',
    'maps/overview',
    'UVU/overview',
    'UVU/Courtyward',
    'Locations/overview',
    'Tent/overview',
    'Before/overview',
    'After/overview',
    'Medical/overview',
    'People/overview',
    'Influencers/overview',
    'Influencers/podcasts',
    'Influencers/x',
    'Influencers/youtube',
    'Media/overview',
    'TPUSA/overview',
    'Videos/overview',
    'Photos/overview',
    'Other/overview',
  ],
};

export default sidebars;
