import csv, math
from collections import Counter, defaultdict
from datetime import date
rows=list(csv.DictReader(open("inversion_matrix.csv")))
pairs=list(csv.DictReader(open("inversion_pairs_wide.csv")))
BK=["SAME_AIRPORT","NEARBY_AIRPORT","SAME_METRO","KNOWN_TRANSIT","DISTANT"]
def yr(r): return r["visit_date"][:4]
years=sorted(set(yr(r) for r in rows)); tails=sorted(set(r["tail"] for r in rows))
L=[]
A=L.append
A("# Inversion cross-tab — foreign-fleet ground-visit days vs all 139 TPUSA/Kirk events\n")
A("Generated by `inversion.py` / `pairs.py` / `crosstab.py` in this scratchpad. Read-only analysis;")
A("nothing under `site/docs/Planes/following` was modified.\n")
A("## What a row is\n")
A("One row = one **(tail, UTC day, airport)** the aircraft was actually recorded ON THE GROUND at,")
A("parsed out of `trace_visit_index.json`. 350 ground-visit records across the six foreign tails collapse")
A("to **135 North-American ground-visit records → 56 unique (tail, day, airport) presence records → 51")
A("unique tail-days at 12 distinct airports.**\n")
A("Distances are great-circle miles from the **airport the plane was on the ground at** to (a) the event")
A("city centroid (US Census 2024 gazetteer, via each `speaking/<slug>.yaml` `event.location.geocode`) and")
A("(b) the event's inferred arrival airport (OurAirports coordinates). Gap is signed days: **negative =")
A("plane was there BEFORE the event, positive = after**; 0 = plane present inside the event's own date span.")
A("Combined score = `dist_mi/100 + |gap_days|/3` — 1.00 is the corner of the 100 mi / 3 day box, lower is better.\n")
A("**5 of the 139 events have no location at all** (`UNKNOWN` / `AMBIGUOUS` city: three 2022 TPUSA Debate")
A("Nights, one 2024 University of Nevada entry, one 2025 student town hall). They cannot be scored")
A("spatially and are excluded — 134 events participate.\n")
A("## Bucket definitions used\n")
A("| Bucket | Test (applied in this precedence order) |")
A("|---|---|")
A("| SAME_AIRPORT | ground airport == the event's own inferred arrival airport, event within ±3 days |")
A("| SAME_METRO | different airport, but same metro string OR the airport is inside that event's own 40-mile radius list, event within ±3 days |")
A("| NEARBY_AIRPORT | different airport, ≤100 mi from the event city, event within ±3 days |")
A("| KNOWN_TRANSIT | no event within 100 mi / ±3 days, and the field is a documented US customs port |")
A("| DISTANT | no event within 100 mi / ±3 days, and not a customs port |")
A("")
A("## 1. Bucket totals (56 presence records)\n")
c=Counter(r["bucket"] for r in rows)
A("| Bucket | Records | Tail-days |")
A("|---|---:|---:|")
for b in BK:
    td=len(set((r["tail"],r["visit_date"]) for r in rows if r["bucket"]==b))
    A(f"| {b} | {c.get(b,0)} | {td} |")
A(f"| **TOTAL** | **{len(rows)}** | **{len(set((r['tail'],r['visit_date']) for r in rows))}** |")
A("")
A("**Nothing landed in NEARBY_AIRPORT.** Across 3.5 years there is not one case of the foreign fleet on the")
A("ground at a field 40–100 miles from a Kirk/TPUSA event within ±3 days. That is the single most direct")
A("test of Bryan's hypothesis 2 and it returns zero.\n")
A("## 2. Bucket × YEAR (this is the hypothesis-2 test)\n")
A("| Year | "+" | ".join(BK)+" | total |")
A("|---|"+"---:|"*(len(BK)+1))
for y in years:
    rr=[r for r in rows if yr(r)==y]
    cc=Counter(r["bucket"] for r in rr)
    A(f"| {y} | "+" | ".join(str(cc.get(b,0)) for b in BK)+f" | {len(rr)} |")
A("")
A("## 3. Bucket × TAIL\n")
A("| Tail | "+" | ".join(BK)+" | total | airports used |")
A("|---|"+"---:|"*(len(BK)+1)+"---|")
for t in tails:
    rr=[r for r in rows if r["tail"]==t]
    cc=Counter(r["bucket"] for r in rr)
    aps=", ".join(f"{k}×{v}" for k,v in Counter(r["ground_airport"] for r in rr).most_common())
    A(f"| {t} | "+" | ".join(str(cc.get(b,0)) for b in BK)+f" | {len(rr)} | {aps} |")
A("")
A("## 4. Bucket × documented mundane reason for the FIELD\n")
A("From `following/airports.csv` (`mro_on_field`, `is_us_customs_port`).\n")
A("| Bucket | Field explanation | Records |")
A("|---|---|---:|")
for (b,f),n in sorted(Counter((r["bucket"],r["field_documented_mundane_reason"]) for r in rows).items()):
    A(f"| {b} | {f} | {n} |")
A("")
A("**Every SAME_AIRPORT and SAME_METRO record is at KPVU (Provo), the field where Duncan Aviation runs a")
A("full-service MRO that `airports.csv` records as holding the Egyptian Air Force maintenance account since")
A("1999.** No presence record in any bucket sits at a field with no documented maintenance or customs reason")
A("to be there, except KLAX / KIAD / MMUN, none of which produced an event match.\n")
A("## 5. Airport baseline — does the fleet's US geography even overlap the event geography?\n")
A("For each field the fleet was on the ground at, how many of the 134 geocoded events fall within a radius")
A("**on any date at all**. This is the ceiling on how many matches were even available.\n")
import json,glob,yaml
FOLL="/Users/bryanstarbuck/BGit/Bryan_git/charlie-kirk/site/docs/Planes/following"
def hav(a,b,c,d):
    R=3958.7613;p1,p2=math.radians(a),math.radians(c);dp=math.radians(c-a);dl=math.radians(d-b)
    h=math.sin(dp/2)**2+math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(min(1,math.sqrt(h)))
EV=[]
for y in sorted(glob.glob(f"{FOLL}/speaking/*.yaml")):
    d=yaml.safe_load(open(y)); g=d["event"]["location"].get("geocode") or {}
    if g.get("lat"): EV.append((g["lat"],g["lon"]))
apts={}
for r in rows: apts.setdefault(r["ground_airport"],[float(r["lat"]),float(r["lon"]),0])[2]
for r in rows: apts[r["ground_airport"]][2]+=1
A("| Field | Presence records | Events ≤40 mi | ≤100 mi | ≤250 mi |")
A("|---|---:|---:|---:|---:|")
for code,(la,lo,n) in sorted(apts.items(), key=lambda x:-x[1][2]):
    A(f"| {code} | {n} | {sum(1 for e in EV if hav(la,lo,*e)<=40)} | {sum(1 for e in EV if hav(la,lo,*e)<=100)} | {sum(1 for e in EV if hav(la,lo,*e)<=250)} |")
A("")
A("KPVU — 20 of the 56 presence records, more than a third of everything the fleet did in North America —")
A("has **2 of 134 events within 100 miles**. KILG, 19 records, has 3. The fleet's American geography and")
A("the event geography barely intersect.\n")
A("## 6. Every visit↔event pair inside 150 mi and ±7 days (the widened net)\n")
A("13 pairs exist in the entire 3.5-year record. All 13 are at ONE metro (Wasatch Front, Utah) and involve")
A("TWO event clusters. All 13 are `CHARLIE_ONLY` events.\n")
A("| Visit date | Tail | Field | Event | Event date | Event city | Event airport | Same field? | Mi to city | Mi to event apt | Gap | In overlaps.csv (date+tail)? |")
A("|---|---|---|---|---|---|---|---|---:|---:|---:|---|")
for p in sorted(pairs,key=lambda x:float(x["score"])):
    A(f"| {p['visit_date']} | {p['tail']} | {p['ground_airport']} | {p['event_slug']} | {p['event_date']} | {p['event_city']} | {p['event_airport']} | {p['same_airport']} | {p['dist_to_event_city_mi']} | {p['dist_to_event_airport_mi']} | {p['gap_days']} | {p['tail_date_in_overlaps_csv']} |")
A("")
A("## 7. Coverage / selection-bias note\n")
A("The archive pull that produced these traces was **event-centred**: 213 of the 284 foreign-fleet trace-days")
A("we hold sit inside some event's ±2-day window, 30 more are the 1st-of-month ADSBX free samples, and only")
A("52 are neither. The search was therefore *biased toward* finding the fleet near events — and it still")
A("found 13 pairs at one metro. The negative result is stronger than the raw counts suggest.")
A("")
A("Conversely, a day the fleet spent parked 300 miles from an event will usually only be in this dataset if")
A("an event happened somewhere in the country that week. Absolute visit counts per field are therefore NOT a")
A("usage census for these aircraft.")
open("inversion_crosstab.md","w").write("\n".join(L)+"\n")
print("\n".join(L))
